In [1]:
import numpy as np
import sys
import csv

# np.set_printoptions(threshold=sys.maxsize)


In [2]:
def fftnoise(f):
    f = np.array(f, dtype='complex')
    Np = (len(f) - 1) // 2
    phases = np.random.rand(Np) * 2 * np.pi
    phases = np.cos(phases) + 1j * np.sin(phases)
    f[1:Np+1] *= phases
    f[-1:-1-Np:-1] = np.conj(f[1:Np+1])
    return np.fft.ifft(f).real

In [3]:
def band_limited_noise(min_freq, max_freq, samples=1024, samplerate=1):
    freqs = np.abs(np.fft.fftfreq(samples, 1/samplerate))
    f = np.zeros(samples)
    idx = np.where(np.logical_and(freqs>=min_freq, freqs<=max_freq))[0]
    f[idx] = 1
    return fftnoise(f)

In [12]:
numSamples = 1200

Noise = np.zeros((101,numSamples))

SampleIdx = np.zeros(numSamples)

lowBand = [0, 300, 700]
highBand = [600, 699, 20000]

for i in range(3):
    for j in range(400):
        C1 = band_limited_noise(lowBand[i],highBand[i] , 100, 48000)
        C1 = np.int8(C1 * (2**15 - 1))
        SampleIdx[j+i*400] = j+i*400
        Noise[0][j+i*400] = i
        for h in range(100):
            Noise[h+1][j+i*400] = C1[h]
            


In [13]:
print(Noise)

[[   0.    0.    0. ...    2.    2.    2.]
 [  59.   14.   80. ...   95.   72.  103.]
 [  84.  -20.  107. ...   -2.  104.  -38.]
 ...
 [ -30. -128.   10. ... -105.   33.   92.]
 [   2.   89.   31. ... -114.  -37.  -93.]
 [  31.   51.   54. ...   77.  -30.  124.]]


In [14]:
# writing to csv file  
with open('CapstoneMachineLearningTrainingInputs.csv', 'w') as csvfile:  
    # creating a csv writer object  
    csvwriter = csv.writer(csvfile)  
        
    # writing the fields  
    csvwriter.writerow(SampleIdx)  
        
    # writing the data rows  
    csvwriter.writerows(Noise)